# Generated by Django 5.1 on 2024-08-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_exercise_workoutplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
